# Generated by Django 5.2 on 2025-04-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../default2_lufpnp', upload_to='images/'),
        ),
    ]
