# Generated by Django 4.2 on 2025-04-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dvajuxx87/image/upload/v1743791155/default2_lufpnp.jpg', upload_to='images/'),
        ),
    ]
