# Generated by Django 4.2.20 on 2025-05-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dvajuxx87/image/upload/v1745667613/media/images/default-upload_yzdrqp.png', null=True, upload_to='images/'),
        ),
    ]
